# Build settings
markdown:  kramdown
permalink: pretty
plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site settings
title: Werner Moraes
email: wernerpm@gmail.com
description: Ramblings about my life
url: "https://wernermoraes.com"
twitter_username: wernerpm
github_username: wernerpm

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-2B85LY1CCT"
    anonymize_ip: false # default
